[build]
  command = "npm run build"
  publish = "dist"

[env]
  VITE_GEMINI_API_KEY = "AIzaSyAcKSzofrU7HrWAJXFTXKVnPJZSa8XiXxI"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
